model:
  name: IMDB-2
  initializer_name: random_uniform
  initializer_args:
    minval: -0.02
    maxval: 0.02
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  target_size: 2
  use_last_output: True
  embedding_size: 500
  cell_type: BasicLSTM
  cells:
    - num_units: 200
    - num_units: 200
  loss_func: sentence_loss
  dataset: imdb-small
train:
  epoch_num: 50
  num_steps: 500
  batch_size: 64
  keep_prob: 0.5
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: Adam
  learning_rate: 0.002 
