model:
  name: LSTM-LARGE
  initializer_name: random_uniform
  initializer_args:
    minval: -0.03
    maxval: 0.03
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 1500
  cell_type: BasicLSTM
  cells:
    - num_units: 1500
      forget_bias: 0.0
    - num_units: 1500
      forget_bias: 0.0
  loss_func: sequence_loss
  dataset: ptb
train:
  epoch_num: 60
  num_steps: 35
  batch_size: 20
  keep_prob: 0.35
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 8.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 4.0 *(1.0 if epoch < 14 else (1/1.15)**(epoch-14))"
