model:
  name: LSTM-PTB
  initializer_name: random_uniform
  initializer_args:
    minval: -0.05
    maxval: 0.05
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 600
  cell_type: BasicLSTM
  cells:
    - num_units: 600
      forget_bias: 0.0
    - num_units: 600
      forget_bias: 0.0
  loss_func: sequence_loss
  dataset: ptb
train:
  epoch_num: 40
  num_steps: 40
  batch_size: 20
  keep_prob: 0.5
  gradient_clip: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: GradientDescent
  learning_rate: "lambda epoch: 5.0 *(1.0 if epoch < 6 else 0.85**(epoch-6))"

