model:
  name: LSTM-LARGE3A
  initializer_name: random_uniform
  initializer_args:
    minval: -0.03
    maxval: 0.03
  input_dtype: int32
  target_dtype: int32
  vocab_size: 10000
  embedding_size: 600
  cell_type: BasicLSTM
  cells:
    - num_units: 600
    - num_units: 600
  loss_func: sequence_loss
  dataset: ptb
train:
  epoch_num: 40
  num_steps: 40
  batch_size: 20
  keep_prob: 0.4
  gradient_cli: global_norm
  gradient_clip_args:
    clip_norm: 5.0
  optimizer: Adam
  learning_rate: 0.0005
